version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: expense-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expense_db
      MYSQL_USER: expense_user
      MYSQL_PASSWORD: expense_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - app-network
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - app-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  backend:
    image: rakeshariveni/expense-tracker-backend:latest
    container_name: expense-tracker
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started
    restart: always
    networks:
      - app-network
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/expense_db
      - SPRING_DATASOURCE_USERNAME=expense_user
      - SPRING_DATASOURCE_PASSWORD=expense_pass
      - SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT=60000
      - SERVER_ADDRESS=0.0.0.0

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /home/ec2-user/expense-tracker/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - /home/ec2-user/grafana-data:/var/lib/grafana
    networks:
      - app-network
    ports:
      - "3000:3000"

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge