# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
# Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
# Enable Prometheus endpoint
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
# Optional (clean output)
management.endpoint.metrics.enabled=true
management.server.port=8080
# Redis (docker container name)
spring.data.redis.host=redis
spring.data.redis.port=6379
# Logging
logging.level.root=INFO
logging.level.com.rakesh.expensetracker=DEBUG
# Kafka
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=expense-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.properties.spring.json.trusted.packages=*
# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rakeshariveni08@gmail.com
spring.mail.password=otvmzygayblzhqrm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true