# DB (local)
spring.datasource.url=jdbc:mysql://localhost:3306/expense_tracker?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis (local docker)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Logging
logging.level.root=INFO
logging.level.com.rakesh.expensetracker=DEBUG