# DB (RDS)
spring.datasource.url=jdbc:mysql://expense-tracker-db.cfg8aq4cq84d.ap-south-1.rds.amazonaws.com:3306/expense_tracker?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=Snoopy4466

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Optional (clean output)
management.endpoint.metrics.enabled=true

# Redis (docker container name)
spring.data.redis.host=redis
spring.data.redis.port=6379

# Logging
logging.level.root=INFO